name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to our Java Notes we appereciate your contribution which makes this repo better please free to add new things' first issue"
        pr-message: "Shazaam..... You done it we are updating right now' first pull request"
